[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/var/run/supervisord.pid
user=root

[program:nojsen]
command=/nojsen/usr/local/bin/repocket
directory=/nojsen
autostart=true
autorestart=true
startretries=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/nojsen",PATH="/nojsen/usr/local/sbin:/nojsen/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",RP_EMAIL="rezanb110110@gmail.com",RP_API_KEY="0af9fbbb-6293-4569-8bb5-fa390ea873dd",NODE_ENV="production",SSL_CERT_FILE="/etc/ssl/certs/ca-certificates.crt"

[program:fjcrose]
command=/app/main
directory=/app
autostart=true
autorestart=true
startretries=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/app",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[program:traffmonetizer]
command=/usr/local/bin/cli start accept --token fRN9va/syiYDtuGB+9RXCT3JXAY2mNQJGNqpKlVtmlI=
autostart=true
autorestart=true
startretries=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/root",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
